model:
  type: resnet50
  num_classes: 32
  pretrained: True

datasets:
  train:
    root: '/home/data/monitor/init/train/'
  val:
    root: '/home/data/monitor/init/val/'

  mean: [0.6078305894330078, 0.5706302081705229, 0.4601289363951588]
  std: [0.1008510393323826, 0.09764929025033584, 0.1044599268983488]

  batch_size: 12

train_param:
  epoch: 200
  save_path: './checkpoints'
  save_interval: 20

  logger_name: 'monitor'
  log_interval_step: 50
  logger_path: '/home/xjm/Code/monitor/log/{name}.txt'

  writer_dir: './writer'
  load_from: '/home/xjm/Code/monitor/checkpoints/0000000200.pth'

inference:
  data_path: '/home/data/monitor_inference/'
  output: '/home/data/monitor_inference2/'
  load_from: '/home/xjm/Code/monitor/checkpoints/0000000200.pth'